# Generated by Django 3.0.5 on 2020-06-15 23:14

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('sosafitosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='ciudad',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='reporte',
            name='ubicacion',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63),
        ),
    ]
