# Generated by Django 3.0.7 on 2020-06-22 16:50

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('sosafitosapp', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='ciudad',
            field=models.CharField(default='Santiago', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='ubicacion',
            field=location_field.models.plain.PlainLocationField(default=0.0, max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='foto',
            field=models.ImageField(default=None, upload_to='Reportes'),
        ),
    ]
