# Generated by Django 3.0.5 on 2020-06-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosafitosapp', '0003_auto_20200615_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='foto',
            field=models.ImageField(default=None, upload_to='Reportes'),
        ),
    ]
