# Generated by Django 3.0.5 on 2020-06-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosafitosapp', '0003_auto_20200615_1924'),
        ('sosafitosapp', '0002_tag'),
    ]

    operations = [
    ]
